<a href="https://colab.research.google.com/github/GuerreroG226/programacion1/blob/main/Tarea_ind.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import os
os.makedirs('Proyecto_Matrices', exist_ok=True)

In [4]:
%%writefile Proyecto_Matrices/operaciones_matrices.py
import numpy as np

def sumar_matrices(A, B):
  A = np.array(A)
  B = np.array(B)
  if A.shape != B.shape:
    raise ValueError("Las matrices deben tener las mismas dimensiones para sumarse.")
  return A + B

def restar_matrices(A, B):
  A = np.array(A)
  B = np.array(B)
  if A.shape != B.shape:
    raise ValueError("Las matrices deben tener las mismas dimensiones para restarse.")
  return A - B

def multiplicar_matrices(A, B):
  A = np.array(A)
  B = np.array(B)
  if A.shape[1] != B.shape[0]:
    raise ValueError("El número de columnas de A debe ser igual al número de filas de B.")
  return np.dot(A, B)

def Hadamard_matrices(A, B):
  A = np.array(A)
  B = np.array(B)
  if A.shape != B.shape:
    raise ValueError("Para el producto Hadamard, las matrices deben tener las mismas dimensiones.")
  return A * B

def producto_Kronecker(A, B):
  A = np.array(A)
  B = np.array(B)
  return np.kron(A, B)

Overwriting Proyecto_Matrices/operaciones_matrices.py


In [33]:
%%writefile Proyecto_Matrices/entrada.py
import numpy as np

def solicitar_matriz(nombre):
    while True:
        try:
            filas = int(input(f"Ingrese número de filas para Matriz {nombre}: "))
            cols = int(input(f"Ingrese número de columnas para Matriz {nombre}: "))
            if filas <= 0 or cols <= 0:
                print("Las dimensiones deben ser mayores a cero.")
                continue
            break
        except ValueError:
            print("Error: Ingrese un número entero válido para las dimensiones.")

    matriz = []
    print(f"Ingrese los elementos de la Matriz {nombre} fila por fila:")
    for i in range(filas):
        while True:
            try:
                fila_str = input(f"Fila {i+1} (separe los {cols} elementos por espacios): ")
                fila = [float(x) for x in fila_str.split()]
                if len(fila) != cols:
                    print(f"Error: Debe ingresar exactamente {cols} elementos.")
                    continue
                matriz.append(fila)
                break
            except ValueError:
                print("Error: Ingrese solo valores numéricos.")

    return np.array(matriz)

def obtener_matrices_AB():
    print("--- Entrada de Matrices ---")
    A = solicitar_matriz("A")
    print("\n")
    B = solicitar_matriz("B")
    return A, B

Overwriting Proyecto_Matrices/entrada.py


In [34]:
from Proyecto_Matrices.entrada import obtener_matrices_AB

A, B = obtener_matrices_AB()

print("\nMatriz A recibida:\n", A)
print("\nMatriz B recibida:\n", B)

--- Entrada de Matrices ---
Ingrese número de filas para Matriz A: 2
Ingrese número de columnas para Matriz A: 2
Ingrese los elementos de la Matriz A fila por fila:
Fila 1 (separe los 2 elementos por espacios): 1 2
Fila 2 (separe los 2 elementos por espacios): 2 1


Ingrese número de filas para Matriz B: 2
Ingrese número de columnas para Matriz B: 2
Ingrese los elementos de la Matriz B fila por fila:
Fila 1 (separe los 2 elementos por espacios): 4 3
Fila 2 (separe los 2 elementos por espacios): 5 6

Matriz A recibida:
 [[1. 2.]
 [2. 1.]]

Matriz B recibida:
 [[4. 3.]
 [5. 6.]]


In [36]:
%%writefile Proyecto_Matrices/menu.py

def mostrar_menu():
    print("\n--- MENU DE OPERACIONES CON MATRICES ---")
    print("1. Suma de matrices")
    print("2. Multiplicación de matrices")
    print("3. Producto de Hadamard")
    print("4. Producto de Kronecker")
    print("5. Salir")

    while True:
        try:
            opcion = int(input("Seleccione una opción: "))
            if 1 <= opcion <= 5:
                return opcion
            else:
                print("Error: opción no válida (debe ser de 1 a 5).")
        except ValueError:
            print("Error: debe ingresar un número entero.")

Writing Proyecto_Matrices/menu.py


In [38]:
%%writefile Proyecto_Matrices/main.py
import Proyecto_Matrices.operaciones_matrices as ops
import Proyecto_Matrices.entrada as entrada
import Proyecto_Matrices.menu as menu

def ejecutar_programa():
    A, B = entrada.obtener_matrices_AB()

    while True:
        opcion = menu.mostrar_menu()

        if opcion == 5:
            print("Saliendo del programa...")
            break

        try:
            resultado = None
            if opcion == 1:
                resultado = ops.sumar_matrices(A, B)
                operacion = "Suma"
            elif opcion == 2:
                resultado = ops.multiplicar_matrices(A, B)
                operacion = "Multiplicación"
            elif opcion == 3:
                resultado = ops.Hadamard_matrices(A, B)
                operacion = "Producto de Hadamard"
            elif opcion == 4:
                resultado = ops.producto_Kronecker(A, B)
                operacion = "Producto de Kronecker"

            print(f"\nResultado de la {operacion}:\n", resultado)
        except ValueError as e:
            print(f"\nError en la operación: {e}")

if __name__ == "__main__":
    ejecutar_programa()

Writing Proyecto_Matrices/main.py


In [40]:
import Proyecto_Matrices.main as proyecto
import importlib
importlib.reload(proyecto)

proyecto.ejecutar_programa()

--- Entrada de Matrices ---
Ingrese número de filas para Matriz A: 2
Ingrese número de columnas para Matriz A: 2
Ingrese los elementos de la Matriz A fila por fila:
Fila 1 (separe los 2 elementos por espacios): 7 4
Fila 2 (separe los 2 elementos por espacios): 6 2


Ingrese número de filas para Matriz B: 2
Ingrese número de columnas para Matriz B: 2
Ingrese los elementos de la Matriz B fila por fila:
Fila 1 (separe los 2 elementos por espacios): 9 8
Fila 2 (separe los 2 elementos por espacios): 1 6

--- MENU DE OPERACIONES CON MATRICES ---
1. Suma de matrices
2. Multiplicación de matrices
3. Producto de Hadamard
4. Producto de Kronecker
5. Salir
Seleccione una opción: 1

Resultado de la Suma:
 [[16. 12.]
 [ 7.  8.]]

--- MENU DE OPERACIONES CON MATRICES ---
1. Suma de matrices
2. Multiplicación de matrices
3. Producto de Hadamard
4. Producto de Kronecker
5. Salir
Seleccione una opción: 2

Resultado de la Multiplicación:
 [[67. 80.]
 [56. 60.]]

--- MENU DE OPERACIONES CON MATRICES ---
